#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DTHREADSAFE=ON \
    -DBUILD_CLAR=OFF \
    -Wno-dev

cmake --build   build
cmake --install build
