#!/bin/sh

# Make a user and group
addgroup -S smtpd 2>/dev/null
addgroup -S smtpq 2>/dev/null
adduser -S -D -H -h /var/empty -s /bin/false -G smtpq -g smtpq smtpq 2>/dev/null
adduser -S -D -H -h /var/empty -s /bin/false -G smtpq -g smtpq smtpq 2>/dev/null

chgrp smtpq /usr/bin/smtpctl
chmod g+s   /usr/bin/smtpctl
