#!/bin/sh

# Make a user and group
addgroup -S dovecot 2>/dev/null
addgroup -S dovenull 2>/dev/null
adduser -S -D -H -h /dev/null -s /bin/nologin -G dovecot -g dovecot dovecot 2>/dev/null
adduser -S -D -H -h /dev/null -s /bin/nologin -G dovenull -g dovenull dovenull 2>/dev/null
