#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-i18n \
    --sysconfdir=/etc \
    --with-httpddir=/var/www

make

# DESTDIR no worky
install -Dm755 archive/rdmsg       "$1/usr/bin/rdmsg"
install -Dm755 src/hypermail       "$1/usr/bin/hypermail"
install -Dm755 archive/msg2archive "$1/usr/bin/msg2archive"
